[tool.briefcase]
project_name = "Sleep GUI"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/sleepgui"
license = "BSD license"
author = 'Angela Kan'
author_email = "angelakan2002@gmail.com"

[tool.briefcase.app.sleepgui]
formal_name = "Sleep GUI"
description = "CruX BCI Project W'21 Team 5"
icon = "src/sleepgui/resources/sleepgui"
sources = ['src/sleepgui']
requires = []


[tool.briefcase.app.sleepgui.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.sleepgui.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.sleepgui.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.sleepgui.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.sleepgui.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
